### ISSUE TITLE
can't restart ghost or use any 'ghost - ***' command

### ISSUE THREAD

**Issue by ghost** [MT-Libraries/ghost-oss-store#12]
```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost status'
An error occurred.
Message: 'Command failed: /bin/sh -c systemctl is-active ghost_mydomain-com
failed
Stack: Error: Command failed: /bin/sh -c systemctl is-active ghost_mydomain-com
failed
    at makeError (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:169:9)
    at module.exports.sync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:338:15)
    at handleShell (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:116:9)
    at Function.module.exports.shellSync (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:361:43)
    at SystemdProcessManager.isRunning (/usr/lib/node_modules/ghost-cli/extensions/systemd/systemd.js:88:19)
    at Instance.running (/usr/lib/node_modules/ghost-cli/lib/instance.js:120:34)
    at Instance.summary (/usr/lib/node_modules/ghost-cli/lib/instance.js:201:19)
    at instances.map (/usr/lib/node_modules/ghost-cli/lib/commands/ls.js:10:38)
    at Array.map (<anonymous>)
    at LsCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/ls.js:9:32)
    at precheck.then (/usr/lib/node_modules/ghost-cli/lib/command.js:159:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Code: 3
```

**Comment by hxsf** [comment]
it looks like a ghost-cli error.

if you disable the ghost-oss-store plugin, and the command still fail, you should ask help from ghost-cli project, or reopen this issue.

**Comment by ghost** [comment]
I have disabled the ghost-oss-store plugin, and everything works fine.
I'm not clear which directory to install the module?

- /***/***/ghost/content/storage

- /***/***/ghost/content/adapters/storage

- /***/***/ghost/versions/1.21.4/content/adapters/storage

**Comment by hxsf** [comment]
It will look like `ghost/content/adapters/storage/ghost-oss-store` .

But i never used this with ghost-cli. I will test it later.  can tell me the version of your ghost-cli and ghost ?

**Comment by lzy-wy** [comment]
Ghost-CLI version: 1.5.2
Ghost Version: 1.21.4

**Comment by ghost** [comment]
@hxsf 
Ghost-CLI version: 1.5.2
Ghost Version: 1.21.4

**Comment by q1an1x** [comment]
Getting the same error after installing ghost-oss-store plugin.

```
Running sudo command: systemctl is-active ghost_domain-com
A ProcessError occurred.

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_domain-com

failed

Exit code: 3


Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v6.14.2
    Ghost-CLI Version: 1.7.2
    Environment: production
    Command: 'ghost start'

```

**Comment by hxsf** [comment]
![In vm](https://user-images.githubusercontent.com/7581607/39617981-5f401d78-4fb4-11e8-8fc3-3ec13797cb9f.png)

In my test, it works good.

Maybe something else cause the error ?

If you have other info, reopen this issue.
:)
