### ISSUE TITLE
Error: Cannot find module '/var/lib/ghost/versions/1.23.0/core/server/adapters/storage/oss-store'

### ISSUE THREAD

**Issue by donot-wong** [MT-Libraries/ghost-oss-store#14]
```
We cannot find your adapter in: /var/lib/ghost/content/adapters/storage/ or: /var/lib/ghost/versions/1.23.0/core/server/adapters/storage/
IncorrectUsageError: We detected a misuse. Please read the stack trace.
    at new IncorrectUsageError (/var/lib/ghost/versions/1.23.0/node_modules/ghost-ignition/lib/errors/index.js:79:23)
    at Object.getStorage (/var/lib/ghost/versions/1.23.0/core/server/adapters/storage/index.js:60:19)
    at setupSiteApp (/var/lib/ghost/versions/1.23.0/core/server/web/site/app.js:74:73)
    at setupParentApp (/var/lib/ghost/versions/1.23.0/core/server/web/parent-app.js:54:36)
    at /var/lib/ghost/versions/1.23.0/core/server/index.js:84:48
    at tryCatcher (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:693:18)

Error: Cannot find module '/var/lib/ghost/versions/1.23.0/core/server/adapters/storage/oss-store'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.getStorage (/var/lib/ghost/versions/1.23.0/core/server/adapters/storage/index.js:57:42)
    at setupSiteApp (/var/lib/ghost/versions/1.23.0/core/server/web/site/app.js:74:73)
    at setupParentApp (/var/lib/ghost/versions/1.23.0/core/server/web/parent-app.js:54:36)
    at /var/lib/ghost/versions/1.23.0/core/server/index.js:84:48
    at tryCatcher (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/lib/ghost/versions/1.23.0/node_modules/bluebird/js/release/promise_array.js:144:14)
```

**Comment by hxsf** [comment]
Do you clone this project into `/var/lib/ghost/content/adapters/storage` ?
