### ISSUE TITLE
配置完config.production.json后，出错无法打开，附production.error.log

### ISSUE THREAD

**Issue by myinsane** [MT-Libraries/ghost-oss-store#15]
{"name":"Log","hostname":"ubuntu","pid":27979,"level":50,"err":{"id":"8f2c4ed0-723c-11e8-9846-f9cf5235d1a3","domain":"https://www.wanily.com","code":"MODULE_NOT_FOUND","name":"IncorrectUsageError","statusCode":400,"level":"critical","message":"We detected a misuse. Please read the stack trace.","context":"We cannot find your adapter in: /www/wwwroot/wanily/content/adapters/storage/ or: /www/wwwroot/wanily/core/server/adapters/storage/","stack":"IncorrectUsageError: We detected a misuse. Please read the stack trace.\n    at new IncorrectUsageError (/www/wwwroot/wanily/node_modules/ghost-ignition/lib/errors/index.js:79:23)\n    at Object.getStorage (/www/wwwroot/wanily/core/server/adapters/storage/index.js:60:19)\n    at setupSiteApp (/www/wwwroot/wanily/core/server/web/site/app.js:74:73)\n    at setupParentApp (/www/wwwroot/wanily/core/server/web/parent-app.js:54:36)\n    at /www/wwwroot/wanily/core/server/index.js:82:48\n    at tryCatcher (/www/wwwroot/wanily/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:693:18)\n\nError: Cannot find module '/www/wwwroot/wanily/core/server/adapters/storage/ghost-oss-store'\n    at Function.Module._resolveFilename (module.js:476:15)\n    at Function.Module._load (module.js:424:25)\n    at Module.require (module.js:504:17)\n    at require (internal/module.js:20:19)\n    at Object.getStorage (/www/wwwroot/wanily/core/server/adapters/storage/index.js:57:42)\n    at setupSiteApp (/www/wwwroot/wanily/core/server/web/site/app.js:74:73)\n    at setupParentApp (/www/wwwroot/wanily/core/server/web/parent-app.js:54:36)\n    at /www/wwwroot/wanily/core/server/index.js:82:48\n    at tryCatcher (/www/wwwroot/wanily/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:693:18)\n    at Promise._fulfill (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise.js:638:18)\n    at PromiseArray._resolve (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/www/wwwroot/wanily/node_modules/bluebird/js/release/promise_array.js:144:14)"},"msg":"We detected a misuse. Please read the stack trace.","time":"2018-06-17T14:41:46.050Z","v":0}

**Comment by myinsane** [comment]
{
    "url": "...",
    ....
        "transports": ["file", "stdout"]
    },
    "storage": {
        "active": "ghost-oss-store",
        "ghost-oss-store": {
            "accessKeyId": "YOUR ACCESSKEYID",
            "accessKeySecret": "YOUR ACCESSKEYSECRET",
            "bucket": "BUCKET_NAME",
            "region": "YOUR REGION",
            "origin": "YOUR ORIGIN",
            "fileKey": {
                "safeString": true,
                "prefix": "YOUR_PREFIX",
                "suffix": ""
            }
        }
    }
}
